### ISSUE TITLE
With_status and == methods not present

### ISSUE THREAD

**Issue by bhgames** [albertosaurus/power_enum_2#17]
Rails 4.2.5, Ruby 2.2.3
    power_enum (3.0.1)
      activerecord (>= 4.2, < 5.2)
      railties (>= 4.2, < 5.2)

Everything works just fine, except with_status isnt defined and == works classically, not overridden like yours.

```
class CompanyTrainingItem < ActiveRecord::Base
  include PowerEnum::HasEnumerated
  include Authority::Abilities

  has_enumerated :type, class_name: "TrainingItemType", foreign_key: :training_item_type_id, default: :optional
 end
```

```
class TrainingItemType < ActiveRecord::Base
  include PowerEnum::Enumerated
  acts_as_enumerated
end
```

```
create_enum :training_item_type
create_table :company_training_items do |t|
  t.integer :training_item_type_id
end
add_foreign_key :company_training_items, :training_item_types
TrainingItemType.update_enumerations_model do
      ["optional", "first_time_users_only", "every_12_months", "every_24_months", "every_36_months", "hidden"].each do |name|
        TrainingItemType.create name: name
      end
end

```

Get

2.2.3 :014 > CompanyTrainingItem.with_status(:optional)
NoMethodError: undefined method `with_status' for #<Class:0x007fd318a24980>

	from -e:1:in <main>'2.2.3 :015 > CompanyTrainingItem.first.type == :optional

 => false
2.2.3 :016 > CompanyTrainingItem.first.type

 => #<TrainingItemType id: 1, name: "optional">

**Comment by albertosaurus** [comment]
OK, in order:

1) You don't have an enumerated attribute called `status`, you have a `type`. Therefore, what you want to do is `CompanyTrainingItem.with_type(:optional)`.

2) `==` is never changed. You want to use `===`. So `CompanyTrainingType[:optional] === :optional`

3) `CompanyTrainingType.first` is just asking for pain. You just loaded a new instance of the enumerated model into memory. You can do `CompanyTrainingType.all.first` if you have to.

Let me know if this makes sense. I'm going to keep the issue open in the meantime.

**Comment by bhgames** [comment]
Ah yeah okay that was stupid of me to post this. Thanks for clearing it up!

**Comment by albertosaurus** [comment]
Also, you probably want to use some sort of seed management framework. I recommend this one: https://github.com/HornsAndHooves/seed_migrator
